### ISSUE TITLE
Precompiled executable

### ISSUE THREAD

**Issue by UweKeim** [cplotts/wfSpy#2]
Since I'm getting compilation errors (probably my Managed C++ setup is buggy/incomplete), I'm looking for a precompiled executable including the DLLs.

**My question:**

Is there a precompiled executable of wfSpy available somewhere?

_(The one I found on The CodeProject is from 2003 and seems to work only with .NET 1.1)_

**Comment by Fabsky** [comment]
I've a VS 2017 clean installation, with C++ components installed, and I also can't compile the solution:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0006	Metadata file 'D:\Softwares\Tools\wfSpy-4.0\wfspyhook\Debug\wfspyhook.dll' could not be found	wfspylib	D:\Softwares\Tools\wfSpy-4.0\wfspylib\CSC	1	Active
> Error	CS0006	Metadata file 'D:\Softwares\Tools\wfSpy-4.0\wfspyhook\Debug\wfspyhook.dll' could not be found	wfspy	D:\Softwares\Tools\wfSpy-4.0\wfspy\CSC	1	Active
> Error	CS0006	Metadata file 'D:\Softwares\Tools\wfSpy-4.0\wfspylib\bin\Debug\wfspylib.dll' could not be found	wfspy	D:\Softwares\Tools\wfSpy-4.0\wfspy\CSC	1	Active
> Error	MSB8020	The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	wfspyhook	D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets	55	
> 

Has someone an idea of where the problems could come from ?

Thank you

**Comment by cplotts** [comment]
Hmm. I'll see if I can build it.

**Comment by UweKeim** [comment]
I did a rewrite with latest Managed C++, it is compiling and running but actually not working and I was stuck with finding the cause.

It is currently living on our internal Git only, but if anyone might use this as a basis, I would be really glad.

**Comment by cplotts** [comment]
I actually have something compiled and working ... but I still need to look at it some more. Stay tuned.

**Comment by cplotts** [comment]
Alright ... took me a bit to figure out ... but I forgot that you need to compile the x86 version in order to spy on a x86 application ... and the x64 version in order to spy on a x64 application.

I have no idea why people can't compile ... I was able to compile both x86 and x64 with VS 2017.

**Comment by UweKeim** [comment]
Isn’t „works on my machine“ the most important term that every developer needs to know?

**Comment by cplotts** [comment]
I took another look at the build errors above.

> Error MSB8020 The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.

I'm sure that this has to be at the heart of the problem.

I went and double checked ... I do have the Platform Toolset set to 'Visual Studio 2017 (v141)'.

So, again, I don't know why people are having trouble compiling wfSpy. I'll see if I can quickly create some binaries for people to use.

**Comment by cplotts** [comment]
Ok two things. I found an issue where the /clr option wasn't set for the release projects. I normally build in debug :laughing:.

I also created a tag and a release with the binaries that I was able to build.
https://github.com/cplotts/wfSpy/releases/tag/2017.0

I hope this works for everyone!

**Comment by cplotts** [comment]
Let me know if this does work and I'll close this issue.

**Comment by UweKeim** [comment]
Seems to work smoothly. Thanks a lot for helping me on this one.
